services:
  accounts:
    image: "aakasht007/accounts:v1"
    container_name: accounts-ms
    ports :
      - "8080:8080"
    deploy:
      resources:
            limits:
                memory: 700m
    networks:
        - eazybank
  loans:
    image: "aakasht007/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
            limits:
                memory: 700m
    networks:
        - eazybank
  cards:
    image: "aakasht007/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
            limits:
                memory: 700m
    networks:
        - eazybank   
networks:
    eazybank:
        driver: "bridge"